version: "3"

services:
  app:
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
    restart: always
    build: ./
    ports:
      - 3000:8000
    links:
      - mysql
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "1m"
    ports:
      - 3307:3306
    volumes:
      - ./db:/var/lib/mysql/
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']